### ISSUE TITLE
Doesn't work in OSX

### ISSUE THREAD

**Issue by doug-hurst-at-emma** [tsclausing/romnomnom#1]
I've followed the instructions in the README

**Comment by doug-hurst-at-emma** [comment]
I was able to get output by typing this into my terminal screen:

```
$ echo "I II III IV V VI VII VIII IX X"
I II III IV V VI VII VIII IX X
```

**Comment by tsclausing** [comment]
You are doing it right. :+1:

**Comment by tsclausing** [comment]
The README now includes instructions for running a simple repl.
